In [50]:
import pandas as pd
import numpy as np
import re

In [51]:
metode = pd.read_excel("metodepakke-stasjonar.xlsx", sheet_name="Pakke")

In [52]:
dirl  = "Discharge-kopi/"
files = os.listdir(dirl)
files = np.sort(files)
files_txt = [i for i in files if i.endswith('.txt_')]

files_txt = [i[:-5] for i in files if i.endswith('.txt_')]
files_txt.sort(key=int)
files_txt

['200011',
 '200013',
 '200032',
 '200268',
 '200279',
 '200284',
 '200290',
 '200303',
 '200323',
 '600010',
 '1200070',
 '1200171',
 '1200178',
 '1200193',
 '1500049',
 '1500053',
 '1600066',
 '1600075',
 '1800010',
 '1800011',
 '1900079',
 '1900080',
 '1900082',
 '1900096',
 '1900104',
 '2000002',
 '2000011',
 '2200016',
 '2400008',
 '2400009',
 '2500024',
 '2600020',
 '2600021',
 '2600026',
 '3600013',
 '4100001',
 '4100008',
 '4200002',
 '4800005',
 '5000001',
 '5000013',
 '5500004',
 '6200005',
 '6200014',
 '6200015',
 '7200005',
 '7500023',
 '7500028',
 '7600005',
 '7700003',
 '7800008',
 '7900003',
 '8000004',
 '8100001',
 '8200004',
 '8300002',
 '8300006',
 '8300007',
 '8300012',
 '8400011',
 '8400020',
 '8500004',
 '8600010',
 '8600012',
 '8700010',
 '8800004',
 '9100002',
 '9700001',
 '9800004',
 '10100001',
 '10400022',
 '10400023',
 '10500001',
 '10900009',
 '11200008',
 '12400002',
 '12700013',
 '12800005',
 '13300007',
 '13800001',
 '13900020',
 '13900026',
 '13900035',
 '14000002',
 '14800002',
 '15100013',
 '15100015',
 '15200004',
 '15300001',
 '15600008',
 '15600010',
 '15600015',
 '16300007',
 '17200007',
 '17200008',
 '17800001',
 '19600007',
 '19600011',
 '20500006',
 '20600003',
 '20800002',
 '20800003',
 '20900004',
 '21200010',
 '21200049',
 '21300002',
 '22300002',
 '24400002',
 '24700003',
 '30700005',
 '30700007',
 '30800001',
 '31100004',
 '31100006',
 '31100460',
 '31300010']

In [53]:
new_list = []
for i in files_txt:
    new_list.append(i[0:-5]+'.'+i[-5:])

In [54]:
new_list

['2.00011',
 '2.00013',
 '2.00032',
 '2.00268',
 '2.00279',
 '2.00284',
 '2.00290',
 '2.00303',
 '2.00323',
 '6.00010',
 '12.00070',
 '12.00171',
 '12.00178',
 '12.00193',
 '15.00049',
 '15.00053',
 '16.00066',
 '16.00075',
 '18.00010',
 '18.00011',
 '19.00079',
 '19.00080',
 '19.00082',
 '19.00096',
 '19.00104',
 '20.00002',
 '20.00011',
 '22.00016',
 '24.00008',
 '24.00009',
 '25.00024',
 '26.00020',
 '26.00021',
 '26.00026',
 '36.00013',
 '41.00001',
 '41.00008',
 '42.00002',
 '48.00005',
 '50.00001',
 '50.00013',
 '55.00004',
 '62.00005',
 '62.00014',
 '62.00015',
 '72.00005',
 '75.00023',
 '75.00028',
 '76.00005',
 '77.00003',
 '78.00008',
 '79.00003',
 '80.00004',
 '81.00001',
 '82.00004',
 '83.00002',
 '83.00006',
 '83.00007',
 '83.00012',
 '84.00011',
 '84.00020',
 '85.00004',
 '86.00010',
 '86.00012',
 '87.00010',
 '88.00004',
 '91.00002',
 '97.00001',
 '98.00004',
 '101.00001',
 '104.00022',
 '104.00023',
 '105.00001',
 '109.00009',
 '112.00008',
 '124.00002',
 '127.00013',
 '128.00005',
 '133.00007',
 '138.00001',
 '139.00020',
 '139.00026',
 '139.00035',
 '140.00002',
 '148.00002',
 '151.00013',
 '151.00015',
 '152.00004',
 '153.00001',
 '156.00008',
 '156.00010',
 '156.00015',
 '163.00007',
 '172.00007',
 '172.00008',
 '178.00001',
 '196.00007',
 '196.00011',
 '205.00006',
 '206.00003',
 '208.00002',
 '208.00003',
 '209.00004',
 '212.00010',
 '212.00049',
 '213.00002',
 '223.00002',
 '244.00002',
 '247.00003',
 '307.00005',
 '307.00007',
 '308.00001',
 '311.00004',
 '311.00006',
 '311.00460',
 '313.00010']

In [55]:
re_zero = r"[0]{2,4}"
removed_zeros = []
for i in new_list:
    j = i+".0"
    removed_zeros.append(re.sub(re_zero, "", j))
print(
    removed_zeros
)

['2.11.0', '2.13.0', '2.32.0', '2.268.0', '2.279.0', '2.284.0', '2.290.0', '2.303.0', '2.323.0', '6.10.0', '12.70.0', '12.171.0', '12.178.0', '12.193.0', '15.49.0', '15.53.0', '16.66.0', '16.75.0', '18.10.0', '18.11.0', '19.79.0', '19.80.0', '19.82.0', '19.96.0', '19.104.0', '20.2.0', '20.11.0', '22.16.0', '24.8.0', '24.9.0', '25.24.0', '26.20.0', '26.21.0', '26.26.0', '36.13.0', '41.1.0', '41.8.0', '42.2.0', '48.5.0', '50.1.0', '50.13.0', '55.4.0', '62.5.0', '62.14.0', '62.15.0', '72.5.0', '75.23.0', '75.28.0', '76.5.0', '77.3.0', '78.8.0', '79.3.0', '80.4.0', '81.1.0', '82.4.0', '83.2.0', '83.6.0', '83.7.0', '83.12.0', '84.11.0', '84.20.0', '85.4.0', '86.10.0', '86.12.0', '87.10.0', '88.4.0', '91.2.0', '97.1.0', '98.4.0', '101.1.0', '104.22.0', '104.23.0', '105.1.0', '109.9.0', '112.8.0', '124.2.0', '127.13.0', '128.5.0', '133.7.0', '138.1.0', '139.20.0', '139.26.0', '139.35.0', '140.2.0', '148.2.0', '151.13.0', '151.15.0', '152.4.0', '153.1.0', '156.8.0', '156.10.0', '156.15.0', '163.7.0', '172.7.0', '172.8.0', '178.1.0', '196.7.0', '196.11.0', '205.6.0', '206.3.0', '208.2.0', '208.3.0', '209.4.0', '212.10.0', '212.49.0', '213.2.0', '223.2.0', '244.2.0', '247.3.0', '307.5.0', '307.7.0', '308.1.0', '311.4.0', '311.6.0', '311.460.0', '313.10.0']

In [56]:
len(removed_zeros)

116

SÃ¸ke etter stasjonar i excel--ark:

In [57]:
my_st = pd.read_excel('catchments_parameter_2016_NR.xlsx', na_values=-999)
my_st

,regine_area,main_no,point_no,station_name,station_status_key,latitide,longitude,utm_east_z33,utm_north_z33,AARSTILSIG,...,perc_glacier,perc_lake,perc_mountain,perc_urban,utm_zone_gravi,utm_east_gravi,utm_north_gravi,utm_zone_inlet,utm_east_inlet,utm_north_inlet
0,2,1,0,HÃ¥dammen,1,61.054771,12.020735,339180,6772548,24.98,...,0.00,1.200000,0.000000,0.00,33.0,335832.0,6774842.0,33.0,331246.0,6778242.0
1,2,10,0,Sogna,1,60.169624,11.063625,281650,6676813,"10,4",...,0.00,0.000000,0.000000,8.71,33.0,282473.0,6680134.0,33.0,281708.0,6682361.0
2,2,11,0,NarsjÃ¸,1,62.361317,11.478783,317821,6919394,70.93,...,0.00,3.120000,48.130001,0.00,33.0,320761.0,6912838.0,33.0,325149.0,6903553.0
3,2,13,0,Nedre Sjodalsvatn,1,61.560272,8.927067,177672,6840237,581.400024,...,9.04,9.260000,71.480003,0.00,33.0,160285.0,6832658.0,33.0,142130.0,6840583.0
4,2,15,0,Breiddalsvatn ndf.,1,62.004616,7.638808,115094,6896570,176.949997,...,0.88,11.000000,85.269997,0.00,33.0,107119.0,6900739.0,33.0,95464.0,6900835.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,308,1,0,Lenglingen,1,64.244873,13.760306,439898,7124887,464.880005,...,0.00,8.070000,24.830000,0.00,NaN,NaN,NaN,NaN,NaN,NaN
456,311,4,0,Femundsenden (Femunden),1,61.919960,11.940043,339350,6869050,810,...,0.00,18.459999,27.040001,0.00,NaN,NaN,NaN,NaN,NaN,NaN
457,311,6,0,Nybergsund,1,61.259079,12.322496,356394,6794588,2155.310059,...,0.00,9.850000,26.690001,0.06,NaN,NaN,NaN,NaN,NaN,NaN
458,311,460,0,Engeren,1,61.664879,12.018348,342156,6840464,231.679993,...,0.00,4.070000,28.240000,0.04,NaN,NaN,NaN,NaN,NaN,NaN
459,313,8,0,Holmen bru,1,60.096237,12.320405,351000,6665150,183.110001,...,0.00,8.310000,0.000000,0.04,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
testdf = pd.DataFrame()
splitnr = r"\d+(?=.)"
not_added = []
test = []
for i in removed_zeros:
    test = re.findall(splitnr, i)
    test2=[]
    for j in test:
        test2.append(int(j))
    find_regine = my_st.loc[my_st['regine_area'] == test2[0]]
    find_mainno = find_regine.loc[find_regine['main_no'] == test2[1]]
    try:
        df2 = {'St_nr': i, 'Regine': int(find_mainno['regine_area']), 'Main_nr': int(find_mainno['main_no']), 'Stasjonsnamn':  find_mainno['station_name'].to_string(index=False), 'Areal': int(find_mainno['area_total']), 'Breiddegrad': (find_mainno['latitide']).to_string(index=False), 'Lengdegrad': (find_mainno['longitude']).to_string(index=False), 'perc_agricul': int(find_mainno['perc_agricul']), 'perc_bog': int(find_mainno['perc_bog']), 'perc_eff_lake': int(find_mainno['perc_eff_lake']), 'perc_forest': int(find_mainno['perc_forest']), 'perc_glacier': int(find_mainno['perc_glacier']), 'perc_lake': int(find_mainno['perc_lake']), 'perc_mountain': int(find_mainno['perc_mountain']), 'perc_urban': int(find_mainno['perc_urban']), 'height_minimum': int(find_mainno['height_minimum']), 'height_maximum': int(find_mainno['height_maximum']), 'length_km_basin': int(find_mainno['length_km_basin'])}
        testdf = testdf.append(df2, ignore_index = True)
    except:
        not_added.append(i)
        print('This station was skipped:', i)
        continue
    print('Added station '+ i + ' to Dataframe' )

Added station 2.11.0 to Dataframe
Added station 2.13.0 to Dataframe
Added station 2.32.0 to Dataframe
Added station 2.268.0 to Dataframe
Added station 2.279.0 to Dataframe
Added station 2.284.0 to Dataframe
Added station 2.290.0 to Dataframe
This station was skipped: 2.303.0
Added station 2.323.0 to Dataframe
Added station 6.10.0 to Dataframe
Added station 12.70.0 to Dataframe
Added station 12.171.0 to Dataframe
Added station 12.178.0 to Dataframe
Added station 12.193.0 to Dataframe
Added station 15.49.0 to Dataframe
Added station 15.53.0 to Dataframe
Added station 16.66.0 to Dataframe
Added station 16.75.0 to Dataframe
Added station 18.10.0 to Dataframe
Added station 18.11.0 to Dataframe
Added station 19.79.0 to Dataframe
Added station 19.80.0 to Dataframe
Added station 19.82.0 to Dataframe
Added station 19.96.0 to Dataframe
Added station 19.104.0 to Dataframe
Added station 20.2.0 to Dataframe
Added station 20.11.0 to Dataframe
Added station 22.16.0 to Dataframe
Added station 24.8.0 to Dataframe
Added station 24.9.0 to Dataframe
This station was skipped: 25.24.0
Added station 26.20.0 to Dataframe
Added station 26.21.0 to Dataframe
Added station 26.26.0 to Dataframe
Added station 36.13.0 to Dataframe
Added station 41.1.0 to Dataframe
This station was skipped: 41.8.0
Added station 42.2.0 to Dataframe
Added station 48.5.0 to Dataframe
Added station 50.1.0 to Dataframe
This station was skipped: 50.13.0
Added station 55.4.0 to Dataframe
Added station 62.5.0 to Dataframe
Added station 62.14.0 to Dataframe
Added station 62.15.0 to Dataframe
Added station 72.5.0 to Dataframe
Added station 75.23.0 to Dataframe
Added station 75.28.0 to Dataframe
Added station 76.5.0 to Dataframe
Added station 77.3.0 to Dataframe
Added station 78.8.0 to Dataframe
Added station 79.3.0 to Dataframe
Added station 80.4.0 to Dataframe
Added station 81.1.0 to Dataframe
Added station 82.4.0 to Dataframe
Added station 83.2.0 to Dataframe
Added station 83.6.0 to Dataframe
Added station 83.7.0 to Dataframe
Added station 83.12.0 to Dataframe
This station was skipped: 84.11.0
Added station 84.20.0 to Dataframe
Added station 85.4.0 to Dataframe
Added station 86.10.0 to Dataframe
Added station 86.12.0 to Dataframe
Added station 87.10.0 to Dataframe
Added station 88.4.0 to Dataframe
Added station 91.2.0 to Dataframe
Added station 97.1.0 to Dataframe
Added station 98.4.0 to Dataframe
Added station 101.1.0 to Dataframe
Added station 104.22.0 to Dataframe
Added station 104.23.0 to Dataframe
Added station 105.1.0 to Dataframe
Added station 109.9.0 to Dataframe
This station was skipped: 112.8.0
Added station 124.2.0 to Dataframe
Added station 127.13.0 to Dataframe
This station was skipped: 128.5.0
Added station 133.7.0 to Dataframe
Added station 138.1.0 to Dataframe
Added station 139.20.0 to Dataframe
This station was skipped: 139.26.0
Added station 139.35.0 to Dataframe
Added station 140.2.0 to Dataframe
Added station 148.2.0 to Dataframe
This station was skipped: 151.13.0
Added station 151.15.0 to Dataframe
Added station 152.4.0 to Dataframe
Added station 153.1.0 to Dataframe
Added station 156.8.0 to Dataframe
Added station 156.10.0 to Dataframe
Added station 156.15.0 to Dataframe
Added station 163.7.0 to Dataframe
Added station 172.7.0 to Dataframe
Added station 172.8.0 to Dataframe
Added station 178.1.0 to Dataframe
Added station 196.7.0 to Dataframe
Added station 196.11.0 to Dataframe
This station was skipped: 205.6.0
Added station 206.3.0 to Dataframe
Added station 208.2.0 to Dataframe
Added station 208.3.0 to Dataframe
Added station 209.4.0 to Dataframe
Added station 212.10.0 to Dataframe
Added station 212.49.0 to Dataframe
Added station 213.2.0 to Dataframe
This station was skipped: 223.2.0
Added station 244.2.0 to Dataframe
This station was skipped: 247.3.0
Added station 307.5.0 to Dataframe
Added station 307.7.0 to Dataframe
Added station 308.1.0 to Dataframe
Added station 311.4.0 to Dataframe
Added station 311.6.0 to Dataframe
Added station 311.460.0 to Dataframe
This station was skipped: 313.10.0

In [59]:
not_added

['2.303.0',
 '25.24.0',
 '41.8.0',
 '50.13.0',
 '84.11.0',
 '112.8.0',
 '128.5.0',
 '139.26.0',
 '151.13.0',
 '205.6.0',
 '223.2.0',
 '247.3.0',
 '313.10.0']

In [60]:
import json
import requests

In [61]:
#url = "https://hydapi.nve.no/api/v1/Stations?StationId=313.10.0&Active=0" 
head = {"Accept": "application/json",  "X-API-Key": "rjaZ9eZu70y6Cwe3/93DRA=="}

In [62]:
url = "https://hydapi.nve.no/api/v1/Stations?StationId="+"25.24.0"+"&Active=0" 
r = requests.get(url = url, headers=head)
r_res = r.json()
r_data = r_res['data']
r_data

[{'stationId': '25.24.0',
  'stationName': 'Gjuvvatn',
  'latitude': 59.15918,
  'longitude': 7.21481,
  'utmEast_Z33': 55441,
  'utmNorth_Z33': 6583769,
  'masl': 952,
  'riverName': 'Kvina',
  'councilNumber': '4221',
  'councilName': 'Valle',
  'countyName': 'Agder',
  'drainageBasinKey': 879,
  'hierarchy': 'Kvina',
  'lakeArea': 0,
  'lakeName': '',
  'lakeNo': 1381,
  'regineNo': '025.M4',
  'reservoirNo': '',
  'reservoirName': '',
  'stationTypeName': 'Privat, pÃ¥lagt',
  'stationStatusName': 'Aktiv',
  'drainageBasinArea': 96.98,
  'drainageBasinAreaNorway': 96.98,
  'gradient1085': 15.78,
  'gradientBasin': 24.27,
  'gradientRiver': 20.48,
  'heightMinimum': 950,
  'heightHypso10': 1020,
  'heightHypso20': 1041,
  'heightHypso30': 1074,
  'heightHypso40': 1106,
  'heightHypso50': 1139,
  'heightHypso60': 1175,
  'heightHypso70': 1219,
  'heightHypso80': 1271,
  'heightHypso90': 1314,
  'heightMaximum': 1431,
  'lengthKmBasin': 12.7,
  'lengthKmRiver': 20.61,
  'percentAgricul': 0,
  'percentBog': 0.19,
  'percentEffBog': None,
  'percentEffLake': 6.96,
  'percentForest': 0,
  'percentGlacier': 0,
  'percentLake': 16.4,
  'percentMountain': 83.31,
  'percentUrban': 0,
  'utmZoneGravi': 33,
  'utmEastGravi': 57794,
  'utmNorthGravi': 6586956,
  'utmZoneInlet': 33,
  'utmEastInlet': 57983,
  'utmNorthInlet': 6591079,
  'utmZoneOutlet': None,
  'utmEastOutlet': None,
  'utmNorthOutlet': None,
  'annualRunoff': 193.37,
  'specificDischarge': 63.18,
  'regulationArea': 0,
  'areaReservoirs': 0,
  'volumeReservoirs': 0,
  'regulationPartReservoirs': 0,
  'transferAreaIn': 0,
  'transferAreaOut': 0,
  'reservoirAreaIn': 0,
  'reservoirAreaOut': 0,
  'reservoirVolumeIn': 0,
  'reservoirVolumeOut': 0,
  'remainingArea': 0,
  'numberReservoirs': 0,
  'firstYearRegulation': 1979,
  'catchmentRegTypeName': 'Uregulert',
  'owner': 'SIRA KVINA KRAFTSELSKAP',
  'qNumberOfYears': 44,
  'qStartYear': 1971,
  'qEndYear': 2015,
  'qm': 31.1814,
  'q5': 35.2065,
  'q10': 37.4719,
  'q20': 39.3193,
  'q50': 41.3135,
  'hm': 1.8186,
  'h5': 1.9074,
  'h10': 1.9577,
  'h20': 1.9989,
  'h50': 2.0436,
  'culQm': 31.1814,
  'culQ5': 35.2065,
  'culQ10': 37.4719,
  'culQ20': 39.3193,
  'culQ50': 41.3135,
  'culHm': 1.8186,
  'culH5': 1.9074,
  'culH10': 1.9577,
  'culH20': 1.9989,
  'culH50': 2.0436,
  'seriesList': [{'parameterName': 'Vannstand',
    'parameter': 1000,
    'versionNo': 1,
    'unit': 'm',
    'serieFrom': '1971-04-30T00:00:00',
    'serieTo': None,
    'resolutionList': [{'resTime': 0,
      'method': 'Instantaneous',
      'timeOffset': 0,
      'dataFromTime': '1971-04-30T11:00:00Z',
      'dataToTime': '2021-12-05T12:00:00Z'},
     {'resTime': 60,
      'method': 'Mean',
      'timeOffset': 0,
      'dataFromTime': '1986-09-03T13:00:00Z',
      'dataToTime': '2021-12-05T12:00:00Z'},
     {'resTime': 1440,
      'method': 'Mean',
      'timeOffset': 0,
      'dataFromTime': '1971-04-30T11:00:00Z',
      'dataToTime': '2021-12-04T11:00:00Z'}]},
   {'parameterName': 'VannfÃ¸ring',
    'parameter': 1001,
    'versionNo': 1,
    'unit': 'mÂ³/s',
    'serieFrom': None,
    'serieTo': None,
    'resolutionList': [{'resTime': 0,
      'method': 'Instantaneous',
      'timeOffset': 0,
      'dataFromTime': '1971-04-30T11:00:00Z',
      'dataToTime': '2021-12-05T12:00:00Z'},
     {'resTime': 60,
      'method': 'Mean',
      'timeOffset': 0,
      'dataFromTime': '1986-09-03T13:00:00Z',
      'dataToTime': '2021-12-05T12:00:00Z'},
     {'resTime': 1440,
      'method': 'Mean',
      'timeOffset': 0,
      'dataFromTime': '1971-04-30T11:00:00Z',
      'dataToTime': '2021-12-04T11:00:00Z'}]}]}]

In [63]:
skipped_stations = pd.DataFrame()
do_not_exist = []
for j in not_added:
    try:
        url = "https://hydapi.nve.no/api/v1/Stations?StationId="+j+"&Active=0" 
        r = requests.get(url = url, headers=head)
        r_res = r.json()
        r_data = r_res['data']
        regi_re = r'\..*'
        re_zero2 = r"[0]{1,4}"
        for i in r_data:
            i['regineNo'] = re.sub(re_zero2, "", i['regineNo'])
            i['regineNo'] = re.sub(regi_re, '', i['regineNo'])
            #print(i['regineNo'])
        for i in r_data:
            df = {"St_nr":i['stationId'], 'Stasjonsnamn': i['stationName'], 'Regine': i['regineNo'], 'Areal': i['drainageBasinArea'], 'Breiddegrad': i['latitude'], 'Lengdegrad': i['longitude'], 
            'perc_agricul': i['percentAgricul'], 'perc_bog': i['percentBog'], 'perc_eff_lake': i['percentEffLake'], 'perc_forest': i['percentForest'], 'perc_glacier': i['percentGlacier'], 
            'perc_lake': i['percentLake'], 'perc_mountain': i['percentMountain'], 'perc_urban': i['percentUrban'], 'height_minimum': i['heightMinimum'], 'height_maximum': i['heightMaximum'], 
            'length_km_basin': i['lengthKmBasin']}
            skipped_stations = skipped_stations.append(df, ignore_index = True)
    except:
        do_not_exist.append(j)
        print('This station was skipped:', j)
        continue

This station was skipped: 50.13.0
This station was skipped: 151.13.0

In [64]:
skipped_stations

,Areal,Breiddegrad,Lengdegrad,Regine,St_nr,Stasjonsnamn,height_maximum,height_minimum,length_km_basin,perc_agricul,perc_bog,perc_eff_lake,perc_forest,perc_glacier,perc_lake,perc_mountain,perc_urban
0,493.62,62.08713,9.10184,2,2.303.0,DombÃ¥s,2207.0,575.0,32.93,0.00,2.03,0.09,11.15,0.20,3.24,79.24,0.00
1,96.98,59.15918,7.21481,25,25.24.0,Gjuvvatn,1431.0,950.0,12.70,0.00,0.19,6.96,0.00,0.00,16.40,83.31,0.00
2,27.49,59.72001,6.18786,41,41.8.0,Hellaugvatn,1263.0,271.0,7.03,0.00,0.42,2.01,8.88,0.00,7.76,82.10,0.00
3,233.74,61.53279,5.75214,84,84.11.0,Hovefoss,1469.0,20.0,30.71,3.14,4.94,0.45,26.03,0.03,4.52,55.96,0.03
4,87.83,62.98495,9.40710,112,112.8.0,Rinna,1587.0,453.0,14.46,0.00,6.83,0.57,15.94,0.00,2.28,62.62,0.00
5,477.08,64.01762,11.71813,128,128.5.0,StÃ¸afoss,817.0,78.0,34.47,1.99,19.44,0.30,53.02,0.00,4.79,16.09,0.01
6,494.24,64.38757,12.44005,139,139.26.0,EmbrethÃ¸len,1068.0,138.0,45.41,0.00,10.52,0.04,18.82,0.00,3.24,61.51,0.00
7,110.87,69.17903,20.77847,25,205.6.0,Didnojokka,1173.0,522.0,11.91,0.00,0.05,0.54,0.69,0.00,6.08,92.20,0.00
8,877.14,70.13985,24.76063,223,223.2.0,Lombola,1136.0,58.0,51.09,0.00,3.86,0.12,10.02,0.00,4.00,77.38,0.00
9,128.89,69.65991,30.38412,247,247.3.0,Karpelva,404.0,20.0,18.03,0.34,12.55,0.35,51.25,0.00,4.99,11.97,0.00
10,357.86,59.95464,12.18729,313,313.10.0,Magnor,458.0,127.0,146.87,7.54,5.03,0.34,81.04,0.00,3.91,0.00,0.28

In [65]:
testdf = testdf.append(skipped_stations, ignore_index=True)

In [66]:


testdf#.sort_values(by='Regine')
#testdf.to_excel('Nye_stasjonar4.xlsx')

,Areal,Breiddegrad,Lengdegrad,Main_nr,Regine,St_nr,Stasjonsnamn,height_maximum,height_minimum,length_km_basin,perc_agricul,perc_bog,perc_eff_lake,perc_forest,perc_glacier,perc_lake,perc_mountain,perc_urban
0,119.00,62.361317,11.478783,11.0,2.0,2.11.0,NarsjÃ¸,1593.0,737.0,17.00,0.00,11.00,1.00,23.00,0.0,3.00,48.00,0.00
1,479.00,61.560272,8.927067,13.0,2.0,2.13.0,Nedre Sjodalsvatn,2362.0,940.0,36.00,0.00,1.00,4.00,5.00,9.0,9.00,71.00,0.00
2,463.00,61.85194,10.222119,32.0,2.0,2.32.0,AtnasjÃ¸,2169.0,701.0,33.00,0.00,2.00,1.00,20.00,0.0,1.00,68.00,0.00
3,790.00,61.799549,8.447218,268.0,2.0,2.268.0,Akslen,2462.0,476.0,35.00,0.00,0.00,0.00,11.00,10.0,1.00,71.00,0.00
4,432.00,60.133446,11.080104,279.0,2.0,2.279.0,KrÃ¥kfoss,803.0,105.0,40.00,11.00,4.00,0.00,75.00,0.0,4.00,0.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,494.24,64.38757,12.44005,NaN,139,139.26.0,EmbrethÃ¸len,1068.0,138.0,45.41,0.00,10.52,0.04,18.82,0.0,3.24,61.51,0.00
110,110.87,69.17903,20.77847,NaN,25,205.6.0,Didnojokka,1173.0,522.0,11.91,0.00,0.05,0.54,0.69,0.0,6.08,92.20,0.00
111,877.14,70.13985,24.76063,NaN,223,223.2.0,Lombola,1136.0,58.0,51.09,0.00,3.86,0.12,10.02,0.0,4.00,77.38,0.00
112,128.89,69.65991,30.38412,NaN,247,247.3.0,Karpelva,404.0,20.0,18.03,0.34,12.55,0.35,51.25,0.0,4.99,11.97,0.00
113,357.86,59.95464,12.18729,NaN,313,313.10.0,Magnor,458.0,127.0,146.87,7.54,5.03,0.34,81.04,0.0,3.91,0.00,0.28

In [67]:
splitnr = r"\d+(?=.)"
nr_bet = []
test2=[]
test = re.findall(splitnr, '15.53.0')
test
for j in test:
    test2.append(int(j))
test2

[15, 53]

In [68]:
test = []
test2= []
for i in removed_zeros:
    test = re.findall(splitnr, i)
    for j in test:
        test2.append(int(j))
    find_regine = my_st.loc[my_st['regine_area'] == test2[0]]
    find_mainno =  find_regine.loc[find_regine['main_no'] == test2[1]]

In [69]:
find_regine = my_st.loc[my_st['regine_area'] == test2[0]]
find_mainno =  find_regine.loc[find_regine['main_no'] == test2[1]]
find_mainno['station_name'].to_string(index=False)

'NarsjÃ¸'

In [70]:
metode= pd.read_excel('metodepakke-stasjonar.xlsx', sheet_name='Pakke', na_values=-999)
metode

,St_nr,Regine,Main_nr,Stasjonsnamn,Areal,Breiddegrad,Lengdegrad,Klassifikasjon,perc_agricul,perc_bog,...,perc_glacier,perc_lake,perc_mountain,perc_urban,height_minimum,height_maximum,length_km_basin,length_km_river,gradient_basin,gradient_river
0,200284,2,284,SÃ¦latunga,454.829987,61.884285,9.061226,1,1.06,1.08,...,0.120000,1.64,83.680000,0.02,423,1880,34.389999,45.610001,19.629999,22.980000
1,600010,6,10,Gryta,7.030000,59.987228,10.800658,2,0.00,1.56,...,0.000000,2.84,0.000000,0.00,165,435,3.410000,4.860000,21.040001,43.680000
2,1900079,19,79,GravÃ¥,6.310000,59.234844,8.036406,1,3.80,4.60,...,0.000000,0.32,17.270000,0.00,362,1063,4.530000,5.570000,25.580000,105.400002
3,5500004,55,4,RÃ¸ykenes,50.090000,60.248814,5.441903,3,0.46,0.76,...,0.000000,3.90,31.660000,0.22,53,960,15.920000,18.500000,43.360001,43.810001
4,7200005,72,5,Brekke bru,268.160004,60.849995,7.114255,1,0.29,0.46,...,3.070000,4.18,77.150002,0.00,16,1761,30.450001,48.689999,36.619999,32.330002
5,9100002,91,2,DalsbÃ¸vatn,25.719999,62.162430,5.166490,3,1.32,3.03,...,0.000000,10.19,66.519997,0.04,47,527,7.540000,8.080000,30.500000,20.700001
6,12700013,127,13,Dillfoss,479.640015,63.764202,11.765073,1,1.43,21.26,...,0.000000,2.65,21.150000,0.06,39,1031,33.529999,53.189999,16.660000,10.170000
7,15600008,156,8,Svartisdal,121.980003,66.480888,14.224827,1,0.00,0.10,...,45.849998,6.31,32.150002,0.00,71,1578,14.830000,20.400000,NaN,36.080002
8,19600007,196,7,Ytre FiskelÃ¸svatn,54.419998,69.262978,18.882067,1,1.21,4.60,...,0.000000,20.40,30.910000,0.00,158,1233,10.180000,15.560000,22.940001,11.960000
9,24400002,244,2,Neiden,2947.189941,69.700714,29.321308,1,0.02,19.01,...,0.000000,12.43,7.880000,0.11,32,440,87.540001,141.270004,NaN,2.560000
10,31100460,311,460,Engeren,394.829987,61.664879,12.018348,1,0.94,15.62,...,0.000000,4.07,28.240000,0.04,472,1207,26.190001,NaN,NaN,NaN

In [71]:
df2 = {'St_nr': files_txt[2], 'Regine': int(find_mainno['regine_area']), 'Main_nr': int(find_mainno['main_no']), 'Stasjonsnamn':  find_mainno['station_name'].to_string(index=False), 'Areal': int(find_mainno['area_total']), 'Breiddegrad': int(find_mainno['latitide']), 'Lengdegrad': int(find_mainno['longitude']), 'perc_agricul': int(find_mainno['perc_agricul']), 'perc_bog': int(find_mainno['perc_bog']), 'perc_eff_lake': int(find_mainno['perc_eff_lake']), 'perc_forest': int(find_mainno['perc_forest']), 'perc_glacier': int(find_mainno['perc_glacier']), 'perc_lake': int(find_mainno['perc_lake']), 'perc_mountain': int(find_mainno['perc_mountain']), 'perc_urban': int(find_mainno['perc_urban']), 'height_minimum': int(find_mainno['height_minimum']), 'height_maximum': int(find_mainno['height_maximum']), 'length_km_basin': int(find_mainno['length_km_basin'])}

metode = metode.append(df2, ignore_index = True)
metode = metode.append(skipped_stations, ignore_index=True)
metode

,St_nr,Regine,Main_nr,Stasjonsnamn,Areal,Breiddegrad,Lengdegrad,Klassifikasjon,perc_agricul,perc_bog,...,perc_glacier,perc_lake,perc_mountain,perc_urban,height_minimum,height_maximum,length_km_basin,length_km_river,gradient_basin,gradient_river
0,200284,2,284.0,SÃ¦latunga,454.829987,61.884285,9.061226,1.0,1.06,1.08,...,0.120000,1.64,83.680000,0.02,423.0,1880.0,34.389999,45.610001,19.629999,22.980000
1,600010,6,10.0,Gryta,7.030000,59.987228,10.800658,2.0,0.00,1.56,...,0.000000,2.84,0.000000,0.00,165.0,435.0,3.410000,4.860000,21.040001,43.680000
2,1900079,19,79.0,GravÃ¥,6.310000,59.234844,8.036406,1.0,3.80,4.60,...,0.000000,0.32,17.270000,0.00,362.0,1063.0,4.530000,5.570000,25.580000,105.400002
3,5500004,55,4.0,RÃ¸ykenes,50.090000,60.248814,5.441903,3.0,0.46,0.76,...,0.000000,3.90,31.660000,0.22,53.0,960.0,15.920000,18.500000,43.360001,43.810001
4,7200005,72,5.0,Brekke bru,268.160004,60.849995,7.114255,1.0,0.29,0.46,...,3.070000,4.18,77.150002,0.00,16.0,1761.0,30.450001,48.689999,36.619999,32.330002
5,9100002,91,2.0,DalsbÃ¸vatn,25.719999,62.162430,5.166490,3.0,1.32,3.03,...,0.000000,10.19,66.519997,0.04,47.0,527.0,7.540000,8.080000,30.500000,20.700001
6,12700013,127,13.0,Dillfoss,479.640015,63.764202,11.765073,1.0,1.43,21.26,...,0.000000,2.65,21.150000,0.06,39.0,1031.0,33.529999,53.189999,16.660000,10.170000
7,15600008,156,8.0,Svartisdal,121.980003,66.480888,14.224827,1.0,0.00,0.10,...,45.849998,6.31,32.150002,0.00,71.0,1578.0,14.830000,20.400000,NaN,36.080002
8,19600007,196,7.0,Ytre FiskelÃ¸svatn,54.419998,69.262978,18.882067,1.0,1.21,4.60,...,0.000000,20.40,30.910000,0.00,158.0,1233.0,10.180000,15.560000,22.940001,11.960000
9,24400002,244,2.0,Neiden,2947.189941,69.700714,29.321308,1.0,0.02,19.01,...,0.000000,12.43,7.880000,0.11,32.0,440.0,87.540001,141.270004,NaN,2.560000
10,31100460,311,460.0,Engeren,394.829987,61.664879,12.018348,1.0,0.94,15.62,...,0.000000,4.07,28.240000,0.04,472.0,1207.0,26.190001,NaN,NaN,NaN
11,200032,2,11.0,NarsjÃ¸,119.000000,62.000000,11.000000,NaN,0.00,11.00,...,0.000000,3.00,48.000000,0.00,737.0,1593.0,17.000000,NaN,NaN,NaN
12,2.303.0,2,NaN,DombÃ¥s,493.620000,62.087130,9.101840,NaN,0.00,2.03,...,0.200000,3.24,79.240000,0.00,575.0,2207.0,32.930000,NaN,NaN,NaN
13,25.24.0,25,NaN,Gjuvvatn,96.980000,59.159180,7.214810,NaN,0.00,0.19,...,0.000000,16.40,83.310000,0.00,950.0,1431.0,12.700000,NaN,NaN,NaN
14,41.8.0,41,NaN,Hellaugvatn,27.490000,59.720010,6.187860,NaN,0.00,0.42,...,0.000000,7.76,82.100000,0.00,271.0,1263.0,7.030000,NaN,NaN,NaN
15,84.11.0,84,NaN,Hovefoss,233.740000,61.532790,5.752140,NaN,3.14,4.94,...,0.030000,4.52,55.960000,0.03,20.0,1469.0,30.710000,NaN,NaN,NaN
16,112.8.0,112,NaN,Rinna,87.830000,62.984950,9.407100,NaN,0.00,6.83,...,0.000000,2.28,62.620000,0.00,453.0,1587.0,14.460000,NaN,NaN,NaN
17,128.5.0,128,NaN,StÃ¸afoss,477.080000,64.017620,11.718130,NaN,1.99,19.44,...,0.000000,4.79,16.090000,0.01,78.0,817.0,34.470000,NaN,NaN,NaN
18,139.26.0,139,NaN,EmbrethÃ¸len,494.240000,64.387570,12.440050,NaN,0.00,10.52,...,0.000000,3.24,61.510000,0.00,138.0,1068.0,45.410000,NaN,NaN,NaN
19,205.6.0,25,NaN,Didnojokka,110.870000,69.179030,20.778470,NaN,0.00,0.05,...,0.000000,6.08,92.200000,0.00,522.0,1173.0,11.910000,NaN,NaN,NaN
20,223.2.0,223,NaN,Lombola,877.140000,70.139850,24.760630,NaN,0.00,3.86,...,0.000000,4.00,77.380000,0.00,58.0,1136.0,51.090000,NaN,NaN,NaN
21,247.3.0,247,NaN,Karpelva,128.890000,69.659910,30.384120,NaN,0.34,12.55,...,0.000000,4.99,11.970000,0.00,20.0,404.0,18.030000,NaN,NaN,NaN
22,313.10.0,313,NaN,Magnor,357.860000,59.954640,12.187290,NaN,7.54,5.03,...,0.000000,3.91,0.000000,0.28,127.0,458.0,146.870000,NaN,NaN,NaN

In [72]:
#'gradient_basin': int(find_mainno['gradient_basin']), , 'length_km_river': int(find_mainno['length_km_river']), 'gradient_river': int(find_mainno['gradient_river'])

In [73]:
t = '025.M4'
re_reg = r"\..*$"
new_regine = []
re.

SyntaxError: invalid syntax (<ipython-input-73-dfd13043b161>, line 4)